// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID        int     `json:"id"`
	Title     string  `json:"title"`
	Synopsis  string  `json:"synopsis"`
	Authore   string  `json:"authore"`
	Publisher string  `json:"publisher"`
	Stock     int     `json:"stock"`
	Price     float64 `json:"price"`
	Status    string  `json:"status"`
	CreatedOn float64 `json:"created_on"`
	CreatedBy int     `json:"created_by"`
	UpdatedOn float64 `json:"updated_on"`
	UpdatedBy int     `json:"updated_by"`
}

type BookInput struct {
	Title     string  `json:"title"`
	Synopsis  string  `json:"synopsis"`
	Authore   string  `json:"authore"`
	Publisher string  `json:"publisher"`
	Stock     int     `json:"stock"`
	Price     float64 `json:"price"`
	Status    string  `json:"status"`
}

type Employee struct {
	ID        int     `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Photo     string  `json:"photo"`
	IsActive  bool    `json:"is_active"`
	CreatedOn float64 `json:"created_on"`
	CreatedBy int     `json:"created_by"`
	UpdatedOn float64 `json:"updated_on"`
	UpdatedBy int     `json:"updated_by"`
}

type EmployeeInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Photo    string `json:"photo"`
	IsActive bool   `json:"is_active"`
}

type MutationBook struct {
	CreateBook *Book  `json:"CreateBook"`
	DeleteBook string `json:"DeleteBook"`
	UpdateBook string `json:"UpdateBook"`
}

type MutationEmployee struct {
	CreateEmployee *Employee `json:"CreateEmployee"`
	DeleteEmployee string    `json:"DeleteEmployee"`
	UpdateEmployee string    `json:"UpdateEmployee"`
}

type MutationRole struct {
	CreateRole *Role  `json:"CreateRole"`
	DeleteRole string `json:"DeleteRole"`
	UpdateRole string `json:"UpdateRole"`
}

type QueryBook struct {
	GetAllBooks []*Book `json:"GetAllBooks"`
	GetOneBook  *Book   `json:"GetOneBook"`
}

type QueryEmployee struct {
	GetAllEmployees []*Employee `json:"GetAllEmployees"`
	GetOneEmployee  *Employee   `json:"GetOneEmployee"`
}

type QueryRole struct {
	GetAllRoles []*Role `json:"GetAllRoles"`
	GetOneRole  *Role   `json:"GetOneRole"`
}

type Role struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IsDeleted   bool   `json:"is_deleted"`
}

type RoleInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsDeleted   bool   `json:"is_deleted"`
}
